import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data")

TIPO_CORTO = {
    "awesome-list": "lista curada",
    "educativo": "recurso educativo",
    "framework/librería": "framework/libreria",
    "herramienta/app": "herramienta",
}

# Diccionario tecnico EN->ES para traducir la descripcion original del repo.
# Ordenado: frases largas primero. Se aplica con \b para no romper palabras.
TRAD = [
    ("large language models", "modelos de lenguaje grandes"),
    ("large language model", "modelo de lenguaje grande"),
    ("natural language processing", "procesamiento de lenguaje natural"),
    ("machine learning", "aprendizaje automático"),
    ("deep learning", "aprendizaje profundo"),
    ("computer vision", "visión por computadora"),
    ("artificial intelligence", "inteligencia artificial"),
    ("neural networks", "redes neuronales"),
    ("neural network", "red neuronal"),
    ("language model", "modelo de lenguaje"),
    ("operating system", "sistema operativo"),
    ("file system", "sistema de archivos"),
    ("command line", "línea de comandos"),
    ("command-line", "de línea de comandos"),
    ("web application", "aplicación web"),
    ("web framework", "framework web"),
    ("web server", "servidor web"),
    ("static site", "sitio estático"),
    ("user interface", "interfaz de usuario"),
    ("search engine", "motor de búsqueda"),
    ("game engine", "motor de videojuegos"),
    ("real-time", "en tiempo real"),
    ("real time", "en tiempo real"),
    ("open source", "de código abierto"),
    ("open-source", "de código abierto"),
    ("free programming books", "libros gratuitos de programación"),
    ("free and open", "gratuitos y abiertos"),
    ("build your own", "crea tu propio"),
    ("master programming", "domina la programación"),
    ("coding interview", "entrevista de programación"),
    ("system design", "diseño de sistemas"),
    ("developer roadmap", "hoja de ruta del desarrollador"),
    ("public apis", "APIs públicas"),
    ("awesome lists", "listas curadas"),
    ("awesome list", "lista curada"),
    ("curated list", "lista curada"),
    ("cheat sheet", "hoja de referencia"),
    ("from scratch", "desde cero"),
    ("by recreating", "recreando"),
    ("your favorite", "tus favoritas"),
    ("all kinds of", "todo tipo de"),
    ("interesting topics", "temas interesantes"),
    ("written in", "escrito en"),
    ("based on", "basado en"),
    ("easy to use", "fácil de usar"),
    ("high performance", "alto rendimiento"),
    ("blazing fast", "ultrarrápido"),
    ("cross-platform", "multiplataforma"),
    ("self-hosted", "autohospedado"),
    ("code snippets", "fragmentos de código"),
    ("learn programming", "aprende programación"),
    ("learn how to", "aprende a"),
    ("for developers", "para desarrolladores"),
    ("for humans", "para humanos"),
    ("technologies", "tecnologías"),
    ("technology", "tecnología"),
    ("programming", "la programación"),
    ("developers", "desarrolladores"),
    ("developer", "desarrollador"),
    ("libraries", "librerías"),
    ("library", "librería"),
    ("frameworks", "frameworks"),
    ("framework", "framework"),
    ("toolkit", "kit de herramientas"),
    ("tools", "herramientas"),
    ("tool", "herramienta"),
    ("plugins", "plugins"),
    ("plugin", "plugin"),
    ("extension", "extensión"),
    ("templates", "plantillas"),
    ("template", "plantilla"),
    ("boilerplate", "plantilla base"),
    ("tutorials", "tutoriales"),
    ("tutorial", "tutorial"),
    ("roadmap", "hoja de ruta"),
    ("course", "curso"),
    ("books", "libros"),
    ("book", "libro"),
    ("guide", "guía"),
    ("interview", "entrevista"),
    ("database", "base de datos"),
    ("server", "servidor"),
    ("client", "cliente"),
    ("compiler", "compilador"),
    ("interpreter", "intérprete"),
    ("editor", "editor"),
    ("terminal", "terminal"),
    ("agents", "agentes"),
    ("agent", "agente"),
    ("themes", "temas"),
    ("theme", "tema"),
    ("game", "juego"),
    ("engine", "motor"),
    ("monitoring", "monitoreo"),
    ("monitor", "monitorea"),
    ("deployment", "despliegue"),
    ("deploy", "despliega"),
    ("manage", "gestiona"),
    ("organize", "organiza"),
    ("share", "comparte"),
    ("discover", "descubre"),
    ("explore", "explora"),
    ("master", "domina"),
    ("learn", "aprende"),
    ("build", "construye"),
    ("create", "crea"),
    ("security", "seguridad"),
    ("privacy", "privacidad"),
    ("beautiful", "hermoso"),
    ("powerful", "potente"),
    ("modern", "moderno"),
    ("lightweight", "ligero"),
    ("minimal", "minimalista"),
    ("fastest", "el más rápido"),
    ("fast", "rápido"),
    ("simple", "simple"),
    ("easy", "fácil"),
    ("short", "cortos"),
    ("free", "gratis"),
    ("awesome", ""),
    ("curated", "curada"),
    ("collective", "colectiva"),
    ("complete", "completo"),
    ("ultimate", "definitiva"),
    ("apis", "APIs"),
    ("api", "API"),
    ("javascript", "JavaScript"),
    ("typescript", "TypeScript"),
    ("python", "Python"),
    ("with", "con"),
    ("about", "sobre"),
    ("from", "desde"),
    ("using", "usando"),
    ("into", "en"),
    ("your", "tus"),
    ("free apis", "APIs gratuitas"),
    ("free software", "software gratuito"),
    ("free services", "servicios gratuitos"),
    ("software engineer", "ingeniero de software"),
    ("software development", "desarrollo de software"),
    ("computer science", "ciencias de la computación"),
    ("study plan", "plan de estudios"),
    ("design interview", "entrevista de diseño"),
    ("to become", "para convertirte en"),
    ("to use", "para usar"),
    ("to learn", "para aprender"),
    ("to build", "para construir"),
    ("to help", "para ayudar"),
    ("lets you", "te permite"),
    ("network services", "servicios de red"),
    ("hosted on", "alojados en"),
    ("your own", "tus propios"),
    ("code snippets", "fragmentos de código"),
    ("can be", "pueden ser"),
    ("more than", "más de"),
    ("less than", "menos de"),
    ("such as", "como"),
    ("zero-dependency", "sin dependencias"),
    ("dependency-free", "sin dependencias"),
    ("freely available", "disponibles gratis"),
    ("available", "disponible"),
    ("prep for", "prepárate para"),
    ("applications", "aplicaciones"),
    ("services", "servicios"),
    ("systems", "sistemas"),
    ("servers", "servidores"),
    ("skills", "habilidades"),
    ("workflows", "flujos de trabajo"),
    ("workflow", "flujo de trabajo"),
    ("packages", "paquetes"),
    ("package", "paquete"),
    ("benchmarks", "pruebas de rendimiento"),
    ("benchmark", "prueba de rendimiento"),
    ("snapshots", "instantáneas"),
    ("examples", "ejemplos"),
    ("example", "ejemplo"),
    ("snippets", "fragmentos"),
    ("flashcards", "tarjetas"),
    ("samples", "ejemplos"),
    ("sample", "ejemplo"),
    ("playground", "entorno de pruebas"),
    ("dashboard", "panel"),
    ("registry", "registro"),
    ("gateway", "puerta de enlace"),
    ("manager", "gestor"),
    ("tracker", "rastreador"),
    ("linter", "linter"),
    ("formatter", "formateador"),
    ("parser", "analizador"),
    ("renderer", "renderizador"),
    ("bundler", "empaquetador"),
    ("proxy", "proxy"),
    ("software", "software"),
    ("mathematics", "matemáticas"),
    ("math", "matemáticas"),
    ("codebase", "código base"),
    ("curriculum", "plan de estudios"),
    ("scripts", "scripts"),
    ("script", "script"),
    ("demo", "demo"),
    ("starter", "inicial"),
    ("skeleton", "esqueleto"),
    ("kernel", "núcleo"),
    ("runner", "ejecutor"),
    ("answers", "responde"),
    ("supports", "soporta"),
    ("provides", "provee"),
    ("offers", "ofrece"),
    ("allows", "permite"),
    ("includes", "incluye"),
    ("helps", "ayuda"),
    ("uses", "usa"),
    ("built", "construido"),
    ("powered", "impulsado"),
    ("does", "hace"),
    ("works", "funciona"),
    ("hosted", "alojados"),
    ("distributed", "distribuido"),
    ("scalable", "escalable"),
    ("reliable", "confiable"),
    ("secure", "seguro"),
    ("portable", "portable"),
    ("extensible", "extensible"),
    ("customizable", "personalizable"),
    ("configurable", "configurable"),
    ("declarative", "declarativo"),
    ("reactive", "reactivo"),
    ("functional", "funcional"),
    ("offline", "sin conexión"),
    ("daily", "diario"),
    ("weekly", "semanal"),
    ("automatically", "automáticamente"),
    ("tiny", "diminuto"),
    ("small", "pequeño"),
    ("large", "grande"),
    ("huge", "enorme"),
    ("other", "otros"),
    ("content", "contenido"),
    ("educational", "educativo"),
    ("careers", "carreras"),
    ("grow", "crecer"),
    ("roadmaps", "hojas de ruta"),
    ("guides", "guías"),
    ("interactive", "interactivas"),
    ("help", "ayudar"),
    ("study", "estudio"),
    ("become", "conviértete en"),
    ("should", "deberías"),
    ("want", "quieres"),
    ("do", "hacer"),
    ("which", "que"),
    ("that", "que"),
    ("this", "esto"),
    ("without", "sin"),
    ("within", "dentro de"),
    ("between", "entre"),
    ("across", "en"),
    ("own", "propios"),
    ("really", "realmente"),
    ("things", "cosas"),
    ("install", "instala"),
    ("run", "ejecuta"),
    ("start", "inicia"),
    ("stop", "detiene"),
    ("test", "prueba"),
    ("debug", "depura"),
    ("generate", "genera"),
    ("convert", "convierte"),
    ("transform", "transforma"),
    ("parse", "analiza"),
    ("render", "renderiza"),
    ("compile", "compila"),
    ("train", "entrena"),
    ("predict", "predice"),
    ("classify", "clasifica"),
    ("detect", "detecta"),
    ("track", "rastrea"),
    ("scan", "escanea"),
    ("analyze", "analiza"),
    ("visualize", "visualiza"),
    ("automate", "automatiza"),
    ("simplify", "simplifica"),
    ("accelerate", "acelera"),
    ("optimize", "optimiza"),
    ("improve", "mejora"),
    ("enhance", "mejora"),
    ("extend", "extiende"),
    ("integrate", "integra"),
    ("connect", "conecta"),
    ("sync", "sincroniza"),
    ("backup", "respalda"),
    ("restore", "restaura"),
    ("migrate", "migra"),
    ("and", "y"),
    ("for", "para"),
    ("or", "o"),
    ("system design interview", "entrevista de diseño de sistemas"),
    ("computer science study plan", "plan de estudios de ciencias de la computación"),
    ("design large-scale systems", "diseñar sistemas de gran escala"),
    ("design systems", "diseñar sistemas"),
    ("skills framework", "framework de habilidades"),
    ("agent skill", "habilidad de agente"),
    ("research system", "sistema de investigación"),
    ("web applications", "aplicaciones web"),
    ("large-scale", "de gran escala"),
    ("large scale", "de gran escala"),
    ("complete", "completo"),
    ("definitive", "definitiva"),
    ("list of", "lista de"),
    ("study", "estudio"),
    ("become", "conviértete en"),
    ("methodology", "metodología"),
    ("methodologies", "metodologías"),
    ("agentic", "agéntico"),
    ("autonomous", "autónomo"),
    ("research", "investigación"),
    ("measurable", "medible"),
    ("executable", "ejecutable"),
    ("catalog", "catálogo"),
    ("live", "en vivo"),
    ("components", "componentes"),
    ("component", "componente"),
    ("source", "código fuente"),
    ("compact", "compacto"),
    ("highly", "altamente"),
    ("simplified", "simplificado"),
    ("rounded", "redondeado"),
    ("subtly", "sutilmente"),
    ("mascot", "mascota"),
    ("logos", "logos"),
    ("skill", "habilidad"),
    ("tune", "ajusta"),
    ("games", "juegos"),
    ("one click", "un clic"),
    ("click", "clic"),
    ("native", "nativo"),
    ("routes", "rutas"),
    ("screens", "pantallas"),
    ("browser", "navegador"),
    ("turn", "convierte"),
    ("them", "los"),
    ("their", "sus"),
    ("in", "en"),
    ("list", "lista"),
    ("to design", "diseñar"),
    ("design", "diseño"),
    ("how to", "cómo"),
    ("i want", "quiero"),
    ("to do", "hacer"),
    ("use", "usar"),
    ("does", "hace"),
    ("of", "de"),
]

# Verbos imperativos solo al inicio ("Build fast..." -> "Construye rápido...").
START_VERBS = [
    ("build", "Construye"),
    ("create", "Crea"),
    ("learn", "Aprende"),
    ("master", "Domina"),
    ("discover", "Descubre"),
    ("explore", "Explora"),
    ("share", "Comparte"),
    ("manage", "Gestiona"),
    ("run", "Ejecuta"),
    ("install", "Instala"),
    ("train", "Entrena"),
    ("visualize", "Visualiza"),
    ("automate", "Automatiza"),
    ("simplify", "Simplifica"),
    ("generate", "Genera"),
    ("convert", "Convierte"),
    ("track", "Rastrea"),
    ("organize", "Organiza"),
    ("monitor", "Monitorea"),
    ("deploy", "Despliega"),
]

import re as _re

def traducir(en):
    """Traduce la descripcion original a español claro y corto (offline)."""
    if not en:
        return ""
    t = " ".join((en or "").replace("\n", " ").split())
    t = _re.sub(r"^(A|An|The)\s+", "", t, flags=_re.I)
    for pat, rep in START_VERBS:
        t = _re.sub(r"^" + pat + r"\b", rep, t, flags=_re.I)
    for pat, rep in TRAD:
        t = _re.sub(r"\b" + pat + r"\b", rep, t, flags=_re.I)
    t = _re.sub(r"\s(the|a|an)\s", " ", t, flags=_re.I)
    t = _re.sub(r"\s+", " ", t).strip(" .-")
    if len(t) > 170:
        t = t[:167].rsplit(" ", 1)[0] + "…"
    if not t:
        return ""
    t = t[0].upper() + t[1:]
    if not t.endswith(("…", ".", "!", "?")):
        t += "."
    return t

def miles(n):
    if n >= 1000:
        v = n / 1000
        return ("%g" % round(v, 1)) + " mil"
    return str(n)

def build_es(x):
    # 1) Traduccion clara y corta de lo que REALMENTE hace el repo.
    es = traducir(x.get("description"))
    # 2) Ficha minima, sin invadir: rank + lenguaje + estrellas.
    lang = x.get("language") or "varios lenguajes"
    if lang == "—":
        lang = "varios lenguajes"
    ficha = "#%d · %s · %s★" % (x.get("rank", 0), lang, miles(x.get("stars", 0)))
    if es:
        return es + " " + ficha + "."
    base = "%s de %s en %s" % (
        TIPO_CORTO.get(x.get("tipo"), "Proyecto"),
        (x.get("categoria") or "software"),
        lang,
    )
    return base + " " + ficha + "."

for fn in ("repos.json", "trending.json"):
    p = os.path.join(SRC, fn)
    d = json.load(open(p, encoding="utf-8"))
    for x in d["repos"]:
        x["descripcion_es"] = build_es(x)
    json.dump(d, open(p, "w", encoding="utf-8"), ensure_ascii=False)
    print(fn, len(d["repos"]), "con descripcion_es")
    print("EJ:", d["repos"][0]["full_name"], "->", d["repos"][0]["descripcion_es"][:160].replace("★", "*"))
